DataDog/gohai

network/network.go, network/network_common.go
We stop propagating an error **if No IPv6 address is found**. We just don't
append the IPv6 address to the 'network' map. The payload just contains
IPv4 and and MAC addresses. Before, having no IPv6 was causing the whole
'network' map to be excluded from the payload, which bothered an host 
willing to use the {{ host.ip }} in his monitors.
This solves the issue an org was having because he doesn't have an IPv6
interface enabled on his CentOS6 machines.
=> [network] No error if no IPv6 interface is found

filesystem/filesystem.go
`df` can take ages on gnarly filesystems. Here we timeout and kill the process if it takes an unreasonable amount of time (> 5 seconds)
=> [filesystem] timeout if df takes too long

filesystem/filesystem.go, filesystem/filesystem_test.go
PR #14 actually didn't work as expected, exiting with the following in the event of timeouts:
```
fatal error: all goroutines are asleep - deadlock!
goroutine 1 [chan receive]:
github.com/DataDog/gohai/filesystem.getFileSystemInfo(0x0, 0x0, 0x0, 0x0)
/home/vagrant/workspace/go/src/github.com/DataDog/gohai/filesystem/filesystem.go:49 +0x61a
github.com/DataDog/gohai/filesystem.(*FileSystem).Collect(0x6556d8, 0x0, 0x0, 0x0, 0x0)
/home/vagrant/workspace/go/src/github.com/DataDog/gohai/filesystem/filesystem_common.go:12 +0x43
main.Collect(0xc20803a3f0, 0x0, 0x0)
/home/vagrant/workspace/go/src/github.com/DataDog/gohai/gohai.go:32 +0xe4
main.main()
/home/vagrant/workspace/go/src/github.com/DataDog/gohai/gohai.go:44 +0x1f
goroutine 5 [chan send]:
github.com/DataDog/gohai/filesystem.func·001() …
```
=> Improve signal handling for `df` timeout

README.md, gohai.go, make.go
To build Gohai with the version info, use:
```
go run make.go
```
otherwise the info is blank.
I've also updated our build repos to support this (see related PRs below).
The info is available in the json output and through a cli option.
Example usage:
```
$ gohai --version
Git hash: 95d122d
Git branch: olivielpeau/version
Build date: Tue Dec  1 17:41:55 EST 2015
Go Version: go version go1.4.2 darwin/amd64
```
=> Add version to json output, and cli option

cpu/cpu_darwin.go, cpu/cpu_linux.go, cpu/cpu_windows.go
Gohai reports the number of physical cores on the host; which is does correctly. However, when using AWS, they provision instances with some number of vCPUs, which causes some confusion. Each vCPU is just half of a physical core, so if there are 16 vCPUs on an instance, then gohai will report 8 cores, because there are only 8 physical cores, and 16 logical processors.
When you test this on a Windows AMI with 16 vCPUs, you'll see that wmi shows NumberOfCores at 8 and NumberOfLogicalProcessors at 16.
Shall we add another count for this?
=> [cpu] Add count for number of logical processors

gohai.go, processes/gops/gops.go, processes/gops/process_group.go, processes/gops/process_info.go, processes/gops/process_info_darwin.go, processes/gops/process_info_linux.go, processes/processes.go
- New collector to retrieve info on the top processes running, in a format
that is compatible with the legacy `processes` check of the agent.
Supports Linux and OS X for now.
- Flags to select/exclude the collectors to run
=> Add process collector

cpu/cpu_windows.go
Forgot to add `cpu_logical_processors` to the output for windows.
=> [cpu] Logical processors in windows output

processes/processes.go, processes/processes_common.go, processes/processes_windows.go
The process collector is not compatible with Windows (yet), but gohai should still build and run fine.
This fixes the build and makes this collector return an error on Windows.
=> [processes] Fix build on win32, return error at run time

gohai.go, log.go, make.go, processes/gops/process_info.go
The log level can be specified through the `log-level` cli option
(default: `info`)
Also, makes the `make.go` script support building multiple files.
Supersedes https://github.com/DataDog/gohai/pull/29
**NB**: this requires adding the seelog lib to gohai's software definition in omnibus-software
=> [log] Use the seelog lib, support log levels

cpu/cpu_windows.go
multiply number of cores and virtual processors (HT) by nummber of
responses.
Fixes card [gohai] Windows: report correct number of CPUs on multi-socket
hosts
What does this PR do?
Takes into account the number of physical CPUs when reporting cores/hyperthreading threads. Was always reporting values from a single CPU.
Motivation
Bug reported by customer
Testing Guidelines
An overview on testing
is available in our contribution guidelines.
Additional Notes
Was tested with VMWare workstation emulating two physical CPUs.
=> Check number of lines of response.  Using same algorithm as Linux,

cpu/cpu_darwin.go, gohai.go, memory/memory_darwin.go, platform/platform_common.go, processes/processes_common.go
The checks, specifically the platform check, has an early return if a
portion of the check fails.  This means that the remainder of the
(functional) check is skipped, and available information is missed.
Attempt to return as much information as possible, even if portions of the
check fail.
=> [Windows Gohai] Allow for more complete partial returns.

platform/platform_common.go
If python is not on the PATH, don't fail, just swallow the error.
=> swallow python error for python version

platform/platform_common.go
This wasn't released yet. Do it for 5.17.0
=> Release "swallow python error for python version (#51)"

make.go
Absent vars on linux builds, failed builds on linux and mac. This fixes it.
=> [gohai][make] trying to fix ldflags issue

platform/platform_common.go
Was present since the beginning of the project. Could happen when the
`uname` command returned an error, which may explain why we've only
noticed this recently.
Also did a cursory check on the rest of the project for similar nil dereferences,
didn't find any other.
=> [platform] Fix nil map dereference

platform/platform_common.go
Previous PR (https://github.com/DataDog/gohai/pull/64) didn't fix it because 🤦‍♂️  on my part
The returned error is bubbled up, so that the caller can handle/log it appropriately.
=> Actually fix the nil map dereference

README.md, filesystem/filesystem.go, filesystem/filesystem_test.go
This uses the exec.CommandContext function to handle the timeout properly
Issue was caused by a race condition, process could have exited or not being started when the timeout expired
=> fix filesystem info command timeout logic

network/network_common.go
For backwards compatibility, information collected for other interfaces are in addition to what we already collect. See screenshot below.
https://cl.ly/d40b80942818
Caveats:
- Information can be only retrieved from the UI using the JSON permalink.
- Frontend code will have to be modified if we want to have this information displayed under the hosts's "System Information" section
=> collects network information from other Network Interfaces

gohai.go, gohai_test.go
This fixes a few minor bugs presumably uncovered in recent versions of Go.  See the commits for details.
If desired, I can also enable CircleCI for this repo.
=> Update things for recent Go versions

platform/platform_windows.go
This PR refactors `GetArchInfo` to support Windows 11 and later OSes.
[GetVersion ](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getversionexa) is a deprecated API so [RtlGetVersion ](https://docs.microsoft.com/en-us/windows/win32/devnotes/rtlgetversion) was used instead. `RtlGetVersion` has the added benefit of returning the build number as well. Should this function not return a correct value in the future, we fallback on the registry key like we did before.
For the OS description, the registry key is no longer updated. There is a function called `BrandingFormatString` from `winbrand.dll` which returns the correct OS description. If this DLL is found and this method is present, we use it, otherwise we fallback to the registry key like we did before. …
=> Refactor Windows' GetArchInfo to support Windows 11 and later OS

network/network_common.go
Currently, if a network interface has multiple ip addresses as alias,  they will be overwritten because it cannot have only one.
This PR is support for multiple ip addresses.
=> [network] Add multiple ip addresses per i/f

platform/platform_common.go
A panic happened in a support case on the line `return strings.Trim(values[1], "\r"), nil` (`index out of range [1] with length 0`).
Although we were not able to get more information on the `python -V` output that caused this to happen, let's be safer in this code path.
This code path is not tested (I only tested that the command still works in the nominal case), I'm preparing a separate PR to add some tests and testing facilities in general.
=> [platform] Fix potential panic when collecting python version

.github/workflows/test.yml, filesystem/filesystem_nix_test.go, platform/platform_common.go, platform/platform_common_test.go, processes/gops/gops.go, processes/gops/process_group.go, processes/gops/process_group_test.go, processes/gops/process_info.go, utils/cmd.go
* Add CI with Github workflow, testing with 1 Go version (1.17.x) on linux/macOS/Windows. This requires putting behind unix-only build flags the tests and/or packages that only work on unix platforms.
* Add tests on the Python version collection logic, with a test pattern that we should hopefully be able to re-use in all the places where gohai uses `cmd.Exec`. Tests changes done in https://github.com/DataDog/gohai/pull/87.
=> Test Python version collection + add CI with Github workflow

.github/workflows/test.yml, filesystem/filesystem.go, filesystem/filesystem_darwin.go, filesystem/filesystem_linux.go, go.mod, go.sum
On MacOS 12.3, `df -l -k` produces an output with 6 columns:
```
> df -l -k
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/disk1s5s1 488245288 311248912 176996376  64% /
/dev/disk1s4   488245288 311248912 176996376  64% /System/Volumes/VM
/dev/disk1s2   488245288 311248912 176996376  64% /System/Volumes/Preboot
/dev/disk1s6   488245288 311248912 176996376  64% /System/Volumes/Update
/dev/disk1s5   488245288 311248912 176996376  64% /System/Volumes/Update/mnt1
```
=> Update expectedLength for Darwin

filesystem/filesystem.go, filesystem/filesystem_nix_test.go, go.mod, go.sum
A few things changed here:
* `exec.Cmd#Output` returns output even if there is an error, although this isn't documented.  So, parse that output if it's present, and only return the error if there's no useful data
* Don't parse blank lines as `nil` in the returned array
* Replace `TestSlowGetFileSystemInfo`, which was only testing `MockSlowGetFileSystemInfo` and not any real code, with an actual test.
* Use a newer version of `require` to get ErrorContains.
=> Be more robust to failures in `df`

filesystem/filesystem.go, filesystem/filesystem_nix_test.go
In some cases, df will output warnings/errors among its output.
=> Fix df output parsing with shorter lines

.github/workflows/test.yml
MacOS 10.15 version is deprecated in Github actions and will be removed fully on March 31st (see https://github.com/actions/runner-images/issues/5583).
This PR simply removes the image from the CI.
The image was added by https://github.com/DataDog/gohai/pull/94 because `df` was found to have a different output format on this version of MacOS compared to more recent versions, but actually the format is the same on the Github actions images macos-10.15, macos-11 and macos-12 (see below), so I guess it depends on the version of `df` itself (or maybe some locale) and not really the version of macos.
I edited the CI to simply run `df -lk` on the 3 versions mentioned above and all 3 had the same format
https://github.com/DataDog/gohai/actions/runs/4282036989
Fixes …
=> Remove deprecated macos-10.15 image version in CI

cpu/cpu_windows.go, cpu/cpu_windows_amd64.go, filesystem/filesystem.go, filesystem/filesystem_windows.go, platform/platform_windows.go
This PR is part of the effort to import gohai directly in the agent, for which we have to pass the agent's linters.
It solves the following lint warnings:
- variable unused (typically an error is stored but not used)
- function returns an error but it is not checked
- defer (eg. Close or Free) before checking whether there was an error
- use of deprecated function
- possible unsafe use of `unsafe.Pointer`
Note: some `//nolint` were used for convenience (mostly to ignore warnings about defer-ing functions which return an error), they will be removed as much as possible in future PRs.
Note: requesting review from @DataDog/windows-agent as most of the changes are in windows files.
Jira ticket: https://datadoghq.atlassian.net/browse/ASC-495
=> Fix various error-related lints

cpu/cpu_windows.go, platform/platform_windows.go
https://github.com/DataDog/gohai/pull/169 fixed various unused error lint warnings, but it changed the behavior of some functions, which instead of returning a default value in case of error now don't return the value.
No one is really sure that this is supported by the backend, and it would break users of gohai which might expects these fields to always be there (some pieces of the agent actually do).
This PR reverts this change to be safe.
=> Return default values for fields that were removed in #169
